version: "3.8"

services:   
  apirest:
    restart: always
    build: .
    ports:
      - "4000:3000"
    links:
      - mysqldb   
  mysqldb:
    restart: always
    image: mysql
    ports:
      - "4306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=usuarios_db
    volumes:
      - mysqldb:/var/lib/mysql
volumes:
  mysqldb: